### ISSUE TITLE
Always uses UTF16

### ISSUE THREAD

**Issue by felixfbecker** [fpschultze/Base64#1]
Most tools use UTF8 (and it's the default in PowerShell 6), but this module always uses `[System.Text.Encoding]::Unicode` (UTF16) instead of `[System.Text.Encoding]::UTF8`.
So trying something like this:
```powershell
(kubectl get secret database -o json | ConvertFrom-Json).data.password | ConvertFrom-Base64String
```
Will print a bunch of random chinese characters instead of the actual value, while this will work correctly:
```powershell
(kubectl get secret database -o json | ConvertFrom-Json).data.password | base64 --decode
```

I would propose a `-Encoding` parameter.

**Comment by fpschultze** [comment]
Good catch! I'll fix it

**Comment by parthsha** [comment]
Could you please publish this version to PowerShell Gallery?

**Comment by fpschultze** [comment]
Done
